name: Generate Snake Animation

on:
  schedule: # Roda todo dia à meia-noite
    - cron: "0 0 * * *"
  workflow_dispatch: # Permite rodar manualmente
  push: # ⚡ roda toda vez que você fizer commit no main
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: jheffeson
          outputs: dist/github-contribution-grid-snake.svg

      - name: Subir artefato no branch "output"
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: dist
